### Criar Usuário

POST  http://localhost:3300/users/signup
Content-Type: application/json

{   
    "email": "ricardo@ricardo.com",
    "name": "Ricardo", 
    "password": "12345678",
    "role": "ADMIN"
}

### Login

POST http://localhost:3300/users/login 
Content-Type: application/json

{   
    "email": "ricardo@ricardo.com",
    "password": "12345678"
}

### Criar Banda
POST http://localhost:3300/bands/create
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6Ijg5Y2Q5MzQ0LWI0YjMtNDk5ZC04NmYwLTQ0ZGVkNjUwZGJiZCIsInJvbGUiOiJBRE1JTiIsImlhdCI6MTY3OTAwODc3MCwiZXhwIjoxNjc5MDEyMzcwfQ.60AuSHHPBYvrX0mpCkE6CO5sCdQ33bYWMBKAPrkTjS8
Content-Type: application/json

{
    
    "name": "Legião Urbana",
    "musicGenre": "Rock", 
    "responsible": "Renato Russo"
}

### Ver Bandas Criadas
GET http://localhost:3300/bands/info
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjhhYjdhOTAyLWNmMDUtNDZmOS1hNWM0LWQwYjkxNmFkYTE5ZSIsInJvbGUiOiJBRE1JTiIsImlhdCI6MTY3OTAwNTUyNiwiZXhwIjoxNjc5MDA5MTI2fQ.um19fAikWPycj0JkFZMHIMdwgBlUgCmyH6YxK04osNU
Content-Type: application/json


### Criar Shows

POST http://localhost:3300/show/create 
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6Ijg5Y2Q5MzQ0LWI0YjMtNDk5ZC04NmYwLTQ0ZGVkNjUwZGJiZCIsInJvbGUiOiJBRE1JTiIsImlhdCI6MTY3OTAwODc3MCwiZXhwIjoxNjc5MDEyMzcwfQ.60AuSHHPBYvrX0mpCkE6CO5sCdQ33bYWMBKAPrkTjS8

{
    "bandId" : "855dcc91-4ef0-4ca2-b331-8471138169a8",
    "weekDay": "friday", 
    "startTime": "8:00", 
    "endTime": "10:00",
    "id" : "d4c43186-52ed-4f24-8dba-382a8f742378"
}
### Retorna os shows
