### Criar Usuário

POST http://localhost:3000/user/signup 
Content-Type: application/json

{   
    "email": "exemplo-victor@lbn.com",
    "name": "Victor", 
    "password": "010203",
    "role": "ADMIN"
}

### Login
POST http://localhost:3000/user/login 
Content-Type: application/json

{   
    "email": "exemplo-victor@lbn.com",
    "password": "010203"
}

### Registrar uma Banda
POST http://localhost:3000/user/createBandRegister
{
     
    "name": "Mauricio",
    "music_genre":"ForMetal",
    "responsible": "Bon Jovi",
    "role": "ADMIN"
}